# Generated by Django 4.2.11 on 2024-03-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('attack_type', models.CharField(choices=[('MELEE', 'Melee'), ('RANGED', 'Ranged')], max_length=30)),
                ('speed', models.PositiveSmallIntegerField(default=2)),
                ('about', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('ability', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sidekick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('attack_type', models.CharField(choices=[('MELEE', 'Melee'), ('RANGED', 'Ranged')], max_length=30)),
                ('speed', models.PositiveSmallIntegerField(default=2)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidekicks', to='games.hero')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
