# Generated by Django 4.2.11 on 2024-03-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_battle_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.battle'),
        ),
    ]
